services:
  - type: web
    name: latigion
    env: python
    buildCommand: "pip install -r requirements.txt && yes | python manage.py collectstatic --noinput"
    startCommand: "gunicorn mysite.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: libreria_os
          property: connectionString



